project:
  type: website

website:
  title: "Relatório de Equipe"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - about.qmd
      - atend.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

